name: Release

on:
  push:
    tags:
      - 'v*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  plugin_name: albamn-hskwakr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Copy src directory without unnecessary files
        uses: up9cloud/action-rsync@master
        env:
          MODE: local
          SOURCE: ./src/
          TARGET: ./${{ env.plugin_name }}
          ARGS: -rc --exclude-from=./src/.distignore --delete --delete-excluded

      - name: Change permission of medias directory
        uses: up9cloud/action-rsync@master
        env:
          MODE: local
          SOURCE: ./src/medias
          TARGET: ./${{ env.plugin_name }}/medias
          ARGS: -I --chmod=777

      - name: Compression
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ env.plugin_name }}.zip ${{ env.plugin_name }}

      - name: Change permission of medias directory
        run: |
          chmod 777 ./src/medias
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.plugin_name }}.zip
