name: Release

on:
  push:
    tags:
      - 'v*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: up9cloud/action-rsync@master
        env:
          MODE: local
          SOURCE: ./src/
          TARGET: ./dist
          ARGS: -rc --exclude-from=./src/.distignore --delete --delete-excluded
          
      - name: Run a one-line script
        run: ls -al ./dist
